import { useState, type ReactNode } from 'react';
import { Link, useParams, useSearchParams } from 'react-router-dom';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { ArrowLeft, ArrowUpRight, ChevronDown, ImagePlus, MessageCircle, Plus, Search, ShoppingBag, Ticket, SlidersHorizontal, X } from 'lucide-react';
import { t, useLanguage, getLanguage, relativeTime } from '@/i18n';
import { useMe } from '@/features/auth/hooks/use-me';
import { uploadPostImage } from '@/features/feed/api/feed';
import { StationDialog } from '@/features/stations/station-dialog';
import { categories,countries,read,write,type Offer,type Store,type Comment,type Page } from './api';
import './vitrine.css';

function useRefresh() {const client=useQueryClient(); return ()=>client.invalidateQueries({queryKey:['vitrine']});}
function Message({error}:{error:Error|null}) {return error?<p role="alert">{t(error.message)}</p>:null;}
function Pager({page,pages,change}:{page:number;pages:number;change:(n:number)=>void}) {return pages>1?<nav className="vitrine-pager" aria-label={t('Páginas')}><button disabled={page===1} onClick={()=>change(page-1)}>{t('Anterior')}</button><span>{page} / {pages}</span><button disabled={page===pages} onClick={()=>change(page+1)}>{t('Próxima')}</button></nav>:null;}
function Country({value,change}:{value:string;change:(s:string)=>void}) {return <label className="vitrine-country"><span className="vitrine-sr">{t('País')}</span><select value={value} onChange={e=>change(e.target.value)}>{Object.entries(countries).map(([id,name])=><option key={id} value={id}>{t(name)}</option>)}</select></label>;}
function OfferCard({offer}:{offer:Offer}) {return <Link className="vitrine-card" to={`/vitrine/${offer.id}`}><div className="vitrine-card-image"><img src={offer.imageUrl} alt="" loading="lazy" />{offer.kind==='COUPON'&&<span>{t('Cupom')}</span>}</div><div className="vitrine-card-copy"><small>{offer.store.name}</small><h3>{offer.title}</h3>{offer.priceCents!=null&&<strong>{new Intl.NumberFormat(getLanguage(),{style:'currency',currency:offer.country==='BR'?'BRL':offer.country==='US'?'USD':'EUR'}).format(offer.priceCents/100)}</strong>}{offer.affiliate&&<small>{t('Link de afiliado')}</small>}{offer.moderationStatus!=='APPROVED'&&<small>{t(offer.moderationStatus==='BLOCKED'?'Retirado':'Aguardando moderação')}</small>}{offer.endedAt&&<small>{t('Oferta encerrada')}</small>}</div></Link>;}
function OfferForm({country,close}:{country:string;close:()=>void}) {
  const refresh=useRefresh();const [file,setFile]=useState<File|null>(null);const [kind,setKind]=useState('PRODUCT');
  const stores=useQuery({queryKey:['vitrine','stores',country],queryFn:()=>read<{data:Store[]}>(`/stores?country=${country}`)});
  const save=useMutation({mutationFn:async(data:FormData)=>{if(!file)throw new Error(t('Selecione uma imagem.'));if(file.size>5*1024*1024)throw new Error(t('A imagem deve ter até 5 MB.'));const price=String(data.get('price')??'').replace(',','.');if(kind==='PRODUCT'&&(!Number.isFinite(Number(price))||Number(price)<=0))throw new Error(t('Informe o preço do produto.'));const imageUrl=await uploadPostImage(file);return write('',{country,kind,storeId:data.get('storeId'),category:data.get('category'),title:data.get('title'),description:data.get('description'),url:data.get('url'),imageUrl,affiliate:data.get('affiliate')==='on',...(price?{priceCents:Math.round(Number(price)*100)}:{}),...(kind==='COUPON'?{coupon:data.get('coupon')}:{}),...(data.get('expiresAt')?{expiresAt:new Date(String(data.get('expiresAt'))).toISOString()}: {})});},onSuccess:async()=>{await refresh();close();}});
  return <form className="vitrine-form" onSubmit={e=>{e.preventDefault();if(!save.isPending)save.mutate(new FormData(e.currentTarget));}}>
    <p className="vitrine-required-note">{t('Os campos com * são obrigatórios.')}</p><p>{t('Cada envio aceito utiliza uma das quatro vagas da semana, mesmo se for excluído ou ficar em análise.')}</p>
    <div className="vitrine-tabs"><button type="button" aria-pressed={kind==='PRODUCT'} onClick={()=>setKind('PRODUCT')}>{t('Produtos de lojas')}</button><button type="button" aria-pressed={kind==='COUPON'} onClick={()=>setKind('COUPON')}>{t('Cupons de desconto')}</button></div>
    <label>{t('Loja')} *<select name="storeId" required><option value="">{t('Selecione uma loja')}</option>{stores.data?.data.map(store=><option key={store.id} value={store.id}>{store.name}</option>)}</select></label>
    {stores.isError&&<Message error={stores.error}/>}{stores.data?.data.length===0&&<p>{t('Ainda não há lojas aprovadas neste país. Sugira uma loja para análise.')}</p>}
    <label>{t('Categoria')} *<select name="category" required>{Object.entries(categories).map(([key,name])=><option key={key} value={key}>{t(name)}</option>)}</select></label>
    <label>{t('Título')} *<input name="title" required minLength={3} maxLength={100}/></label>
    <label>{t('Descrição')} *<textarea name="description" required minLength={3} maxLength={1000} rows={3} placeholder={t(kind==='COUPON'?'Explique o benefício, as condições e onde usar o cupom: no site ou no aplicativo da loja.':'Conte o que é o produto e por que vale compartilhar.')}/><small>{t(kind==='COUPON'?'Explique o benefício, as condições e onde usar o cupom: no site ou no aplicativo da loja.':'Conte o que é o produto e por que vale compartilhar.')}</small></label>
    <label>{t('Link direto da loja')} *<input name="url" type="url" required maxLength={2000} placeholder="https://"/><small>{t('Use o link direto da loja selecionada. Links de lojas ainda não aprovadas não podem ser publicados.')}</small></label>
    <label className="vitrine-check"><input type="checkbox" name="affiliate"/>{t('Este é um link de afiliado')}</label>
    {kind==='PRODUCT'?<label>{t('Preço do produto')} ({country==='BR'?'BRL':country==='US'?'USD':'EUR'}) *<input name="price" required type="number" min="0.01" max="1000000" step="0.01"/></label>:<label>{t('Código do cupom')} *<input name="coupon" required maxLength={80}/></label>}
    <label>{t('Validade')}{kind==='COUPON'?' *':` (${t('Opcional')})`}<input name="expiresAt" type="datetime-local" required={kind==='COUPON'}/></label>
    <label className="vitrine-upload"><ImagePlus size={18}/>{file?file.name:t('Foto obrigatória — adicionar imagem')}<input className="vitrine-file" type="file" required accept="image/png,image/jpeg,image/webp,image/gif" onChange={e=>setFile(e.target.files?.[0]??null)}/></label>
    <Message error={save.error}/><button className="vitrine-primary" disabled={save.isPending||!file||!stores.data?.data.length}>{save.isPending?t('Enviando…'):t('Compartilhar oferta')}</button>
  </form>;
}
function SuggestForm({country,close}:{country:string;close:()=>void}) {const save=useMutation({mutationFn:(d:FormData)=>write('/suggestions',{country,name:d.get('name'),url:d.get('url'),details:d.get('details')}),onSuccess:close});return <form className="vitrine-form" onSubmit={e=>{e.preventDefault();save.mutate(new FormData(e.currentTarget));}}><p>{t('Não encontrou uma loja? Envie o site oficial e explique o que ela oferece. A moderação analisará os domínios antes de liberar seus links.')}</p><label>{t('Nome da loja')}<input name="name" minLength={2} maxLength={80} required/></label><label>{t('Site oficial')}<input name="url" type="url" required maxLength={2000}/></label><label>{t('Informações para análise')}<textarea name="details" minLength={10} maxLength={1000} required/></label><Message error={save.error}/><button disabled={save.isPending}>{t('Enviar para análise')}</button></form>;}
export function VitrinePage() {
  useLanguage();const [params,setParams]=useSearchParams();const country=['BR','US','ES'].includes(params.get('country')??'')?params.get('country')!:'BR';const kind=params.get('kind')==='COUPON'?'COUPON':'PRODUCT';const category=params.get('category')??'';const [filtersOpen,setFiltersOpen]=useState(false);const [page,setPage]=useState(1);const [search,setSearch]=useState(params.get('search')??'');
  function update(key:string,value:string){setParams(p=>{value?p.set(key,value):p.delete(key);return p;});setPage(1);setFiltersOpen(false);}
  const query=new URLSearchParams({country,kind,page:String(page)});for(const key of ['category','storeId','authorId','search','mine'])if(params.get(key))query.set(key,params.get(key)!);
  const offers=useQuery({queryKey:['vitrine','offers',query.toString()],queryFn:()=>read<Page<Offer>>(`?${query}`)});
  const quota=useQuery({queryKey:['vitrine','quota'],queryFn:()=>read<{data:{used:number;limit:number;renewsAt:string;canManage:boolean}}>('/quota')});
  const stores=useQuery({queryKey:['vitrine','stores',country],queryFn:()=>read<{data:Store[]}>(`/stores?country=${country}`)});
  const grouped=!category&&!params.get('search')&&!params.get('authorId')&&!params.get('mine');
  return <section className="vitrine">
    <header className="vitrine-heading">
      <div><span className="vitrine-eyebrow">Moment</span><h1><ShoppingBag size={25}/>{t('Vitrine Moment')}</h1><p>{t('Achados da comunidade, nas lojas que você conhece.')}</p></div>
      <div className="vitrine-heading-actions">
        <Country value={country} change={v=>{setParams(p=>{p.set('country',v);p.delete('storeId');return p;});setPage(1);}}/>
        <StationDialog label={t('Indicar uma loja')} title={t('Sugerir uma loja para análise')}>{close=><SuggestForm country={country} close={close}/>}</StationDialog>
      </div>
    </header>
    <details className="vitrine-help"><summary><ShoppingBag size={15}/>{t('Entenda a Vitrine Moment')}<ChevronDown size={14}/></summary><div className="vitrine-intro">
      <div><ShoppingBag size={19}/><p><strong>{t('Encontre um bom achado')}</strong><span>{t('Explore produtos por loja e categoria, como um fone ou um presente.')}</span></p></div>
      <div><Ticket size={19}/><p><strong>{t('Aproveite um cupom')}</strong><span>{t('Confira o benefício e onde usar o desconto na loja indicada.')}</span></p></div>
      <div><MessageCircle size={19}/><p><strong>{t('Compartilhe e converse')}</strong><span>{t('Indique um produto, troque dicas e veja os detalhes antes de ir à loja.')}</span></p></div>
      <p className="vitrine-intro-note">{t('As indicações vêm da comunidade. A compra e o uso dos cupons acontecem nos sites ou aplicativos das lojas aprovadas.')}</p>
    </div></details>
    <div className="vitrine-tools"><form className="vitrine-search" onSubmit={e=>{e.preventDefault();update('search',search);}}><input value={search} onChange={e=>setSearch(e.target.value)} placeholder={t('Buscar ofertas')} aria-label={t('Buscar ofertas')}/><button type="submit" aria-label={t('Buscar')} title={t('Buscar')}><Search size={17}/></button></form><StationDialog label={t('Compartilhar oferta')} icon={<Plus size={16}/>}>{close=><OfferForm country={country} close={close}/>}</StationDialog></div>
    {quota.data&&<p className="vitrine-quota">{t('{used} de 4 publicações nesta semana',{used:quota.data.data.used})} · {t('Renova em')} {new Date(quota.data.data.renewsAt).toLocaleString(getLanguage(),{dateStyle:'short',timeStyle:'short'})}</p>}
    <div className="vitrine-tabs"><button aria-pressed={kind==='PRODUCT'} onClick={()=>update('kind','PRODUCT')}>{t('Produtos de lojas')}</button><button aria-pressed={kind==='COUPON'} onClick={()=>update('kind','COUPON')}>{t('Cupons de desconto')}</button></div>
    <div className="vitrine-view-actions"><button className="vitrine-filter-toggle" aria-expanded={filtersOpen} aria-controls="vitrine-filters" onClick={()=>setFiltersOpen(!filtersOpen)}><SlidersHorizontal size={15}/>{t('Filtros')}</button><details className="vitrine-section-help"><summary>{t('Sobre esta seção')}</summary><p className="vitrine-tab-description">{t(kind==='PRODUCT'?'Links de produtos de lojas aprovadas, com foto, preço e dicas da comunidade.':'Cupons compartilhados pela comunidade, com condições e indicação de onde usar.')}</p></details></div>
    <div className="vitrine-browse">
      <aside id="vitrine-filters" className={`vitrine-filter-sidebar${filtersOpen?' is-open':''}`} aria-label={t('Filtros')}>
        <h2><SlidersHorizontal size={15}/>{t('Filtros')}</h2>
        <label className="vitrine-store-filter">{t('Loja')}<select value={params.get('storeId')??''} onChange={e=>update('storeId',e.target.value)}><option value="">{t('Todas as lojas')}</option>{stores.data?.data.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label>
        <nav className="vitrine-category-list" aria-label={t('Categorias')}><h3>{t('Categorias')}</h3><button aria-pressed={!category} onClick={()=>update('category','')}>{t('Todas as categorias')}</button>{Object.entries(categories).map(([key,name])=><button key={key} aria-pressed={category===key} onClick={()=>update('category',key)}>{t(name)}</button>)}</nav>
        <div className="vitrine-filter-footer"><button aria-pressed={!!params.get('mine')} onClick={()=>update('mine',params.get('mine')?'':'true')}>{t('Minhas ofertas')}</button>{params.get('authorId')&&<button onClick={()=>update('authorId','')}>{t('Todos os autores')}</button>}{quota.data?.data.canManage&&<Link to="/vitrine/review">{t('Revisar vitrine')}</Link>}</div>
      </aside>
      <div className="vitrine-results">

    {offers.isPending&&<p role="status">{t('Carregando...')}</p>}<Message error={offers.error}/>{offers.isError&&<button onClick={()=>offers.refetch()}>{t('Tentar novamente')}</button>}
    {offers.data?.data.length===0&&<div className="vitrine-empty"><ShoppingBag size={30}/><h2>{t('Ainda não há ofertas por aqui')}</h2><p>{t('Escolha outra categoria ou compartilhe um achado de uma loja aprovada.')}</p></div>}
    {grouped?Object.entries(categories).map(([key,name])=>{const rows=offers.data?.data.filter(o=>o.category===key);return rows?.length?<section key={key} className="vitrine-section"><header><h2>{t(name)}</h2><button onClick={()=>update('category',key)}>{t('Ver todos')}</button></header><div className="vitrine-grid">{rows.slice(0,4).map(o=><OfferCard key={o.id} offer={o}/>)}</div></section>:null;}):<div className="vitrine-grid">{offers.data?.data.map(o=><OfferCard key={o.id} offer={o}/>)}</div>}
    <Pager page={page} pages={offers.data?.meta.pages??1} change={setPage}/>
      </div>
    </div>
  </section>;
}

function Report({id,type}:{id:string;type:string}) {const save=useMutation({mutationFn:(reason:string)=>write('/reports',{targetId:id,targetType:type,reason})});return <StationDialog label={t('Denunciar')}>{close=><form className="vitrine-form" onSubmit={e=>{e.preventDefault();save.mutate(String(new FormData(e.currentTarget).get('reason')),{onSuccess:close});}}><label>{t('Motivo da denúncia')}<textarea name="reason" minLength={5} maxLength={1000} required/></label><Message error={save.error}/><button disabled={save.isPending}>{t('Enviar denúncia')}</button></form>}</StationDialog>;}
function CommentForm({id,target,done}:{id:string;target?:string;done?:()=>void}) {const refresh=useRefresh();const [text,setText]=useState('');const send=useMutation({mutationFn:()=>write(`/${id}/comments`,{content:text,replyToId:target}),onSuccess:async()=>{setText('');await refresh();done?.();}});return <form className="vitrine-comment-form" onSubmit={e=>{e.preventDefault();if(text.trim()&&!send.isPending)send.mutate();}}><textarea aria-label={t('Escreva uma resposta…')} placeholder={t('Escreva uma resposta…')} value={text} onChange={e=>setText(e.target.value)} maxLength={220} rows={2}/><footer><small>{text.length}/220</small><button disabled={!text.trim()||send.isPending}>{t('Responder')}</button></footer><Message error={send.error}/>{send.isSuccess&&<p role="status">{t(send.data.message)}</p>}</form>;}
function CommentRow({row,owner,onReply,children}:{row:Comment;owner:string;id:string;onReply:(row:Comment)=>void;children?:ReactNode}) {const me=useMe().data?.data?.user;const refresh=useRefresh();const remove=useMutation({mutationFn:()=>write(`/comments/${row.id}`,undefined,'DELETE'),onSuccess:refresh});return <article className="vitrine-comment"><header><Link to={`/profile/${encodeURIComponent(row.user.username)}`}>{row.user.name}</Link><small>{relativeTime(row.createdAt)}</small></header>{row.replyToName&&<small>{t('Respondendo a {name}',{name:`@${row.replyToName}`})}</small>}<p>{row.content}</p><div className="vitrine-comment-actions"><button onClick={()=>onReply(row)}>{t('Responder')}</button>{me?.id!==row.userId&&<Report id={row.id} type="COMMENT"/>}{(me?.id===row.userId||me?.id===owner)&&<button disabled={remove.isPending} onClick={()=>{if(confirm(t('Excluir esta resposta? Essa ação não pode ser desfeita.')))remove.mutate();}}>{t('Excluir')}</button>}</div><Message error={remove.error}/>{children}</article>;}
function CommentThread({row,owner,id}:{row:Comment;owner:string;id:string}) {const [open,setOpen]=useState(false);const [target,setTarget]=useState<Comment|null>(null);const [page,setPage]=useState(1);const replies=useQuery({queryKey:['vitrine','comments',id,row.id,page],queryFn:()=>read<Page<Comment>>(`/${id}/comments?parentId=${row.id}&page=${page}`),enabled:open});function respond(r:Comment){setOpen(true);setTarget(r);}return <CommentRow row={row} owner={owner} id={id} onReply={respond}>{(row.repliesCount>0||open)&&<button aria-expanded={open} className="vitrine-expand" onClick={()=>setOpen(!open)}><ChevronDown size={14}/>{open?t('Recolher respostas'):t('Ver {count} respostas',{count:row.repliesCount})}</button>}{open&&<div className="vitrine-thread"><Message error={replies.error}/>{replies.isPending&&<p>{t('Carregando...')}</p>}{!replies.isError&&replies.data?.data.map(r=><CommentRow key={r.id} row={r} owner={owner} id={id} onReply={respond}/>)}<Pager page={page} pages={replies.data?.meta.pages??1} change={setPage}/>{target&&<><div className="vitrine-reply-context">{t('Respondendo a {name}',{name:`@${target.user.username}`})}<button aria-label={t('Cancelar')} onClick={()=>setTarget(null)}><X size={15}/></button></div><CommentForm key={target.id} id={id} target={target.id} done={()=>setTarget(null)}/></>}</div>}</CommentRow>;}
function ExternalLink({id,close}:{id:string;close:()=>void}) {const destination=useQuery({queryKey:['vitrine','destination',id],queryFn:()=>read<{data:{url:string;domain:string;store:string}}>(`/${id}/destination`),staleTime:0});return <div className="vitrine-exit"><p>{t('Você está saindo do Moment. A compra será realizada em uma loja externa. Confira o vendedor, o preço e as condições de entrega e devolução. A aprovação do link não garante a oferta.')}</p>{destination.isPending&&<p>{t('Carregando...')}</p>}<Message error={destination.error}/>{!destination.isError&&destination.data&&<><strong>{destination.data.data.store}</strong><span>{destination.data.data.domain}</span><a className="vitrine-primary" href={destination.data.data.url} target="_blank" rel="noopener noreferrer sponsored" onClick={close}>{t('Continuar para a loja')}<ArrowUpRight size={16}/></a></>}<button onClick={close}>{t('Cancelar')}</button></div>;}
export function VitrineDetail() {useLanguage();const {id=''}=useParams();const me=useMe().data?.data?.user;const refresh=useRefresh();const [page,setPage]=useState(1);const query=useQuery({queryKey:['vitrine','offer',id],queryFn:()=>read<{data:Offer}>(`/${id}`)});const o=query.isError?undefined:query.data?.data;const comments=useQuery({queryKey:['vitrine','comments',id,page],queryFn:()=>read<Page<Comment>>(`/${id}/comments?page=${page}`),enabled:o?.moderationStatus==='APPROVED'});const action=useMutation({mutationFn:(remove:boolean)=>write(`/${id}${remove?'':'/end'}`,undefined,remove?'DELETE':'POST'),onSuccess:refresh});return <section className="vitrine"><Link className="vitrine-back" to="/vitrine"><ArrowLeft size={16}/>{t('Vitrine Moment')}</Link>{query.isPending&&<p>{t('Carregando...')}</p>}<Message error={query.error}/>{o&&<><div className="vitrine-detail"><img src={o.imageUrl} alt={o.title}/><div><small>{o.store.name} · {t(categories[o.category as keyof typeof categories])}</small><h1>{o.title}</h1><p>{o.description}</p>{o.coupon&&<p className="vitrine-coupon">{t('Cupom')}: <strong>{o.coupon}</strong></p>}{o.priceCents!=null&&<strong>{new Intl.NumberFormat(getLanguage(),{style:'currency',currency:o.country==='BR'?'BRL':o.country==='US'?'USD':'EUR'}).format(o.priceCents/100)}</strong>}{o.affiliate&&<p className="vitrine-muted">{t('Link de afiliado: quem compartilhou pode receber uma comissão.')}</p>}{o.expiresAt&&<p className="vitrine-muted">{t('Validade')}: {new Date(o.expiresAt).toLocaleString(getLanguage())}</p>}{o.endedAt||(o.expiresAt&&new Date(o.expiresAt)<=new Date())?<p>{t('Oferta encerrada')}</p>:o.moderationStatus==='APPROVED'?<StationDialog label={t('Ir para a loja')} title={t('Você está saindo do Moment')}>{close=><ExternalLink id={id} close={close}/>}</StationDialog>:<p>{t('Aguardando moderação')}</p>}<p><Link to={`/vitrine?country=${o.country}&kind=${o.kind}&authorId=${o.userId}`}>{t('Ofertas de {name}',{name:o.user.name})}</Link></p><div className="vitrine-options">{me?.id===o.userId?<><button disabled={action.isPending||!!o.endedAt} onClick={()=>action.mutate(false)}>{t('Encerrar oferta')}</button><button disabled={action.isPending} onClick={()=>{if(confirm(t('Excluir não devolve a cota. Continuar?')))action.mutate(true);}}>{t('Excluir')}</button></>:<Report id={id} type="OFFER"/>}</div><Message error={action.error}/></div></div>{o.moderationStatus==='APPROVED'&&<section className="vitrine-conversation"><h2>{t('Comentários')}</h2><CommentForm id={id}/><Message error={comments.error}/>{comments.data?.data.map(row=><CommentThread key={row.id} id={id} owner={o.userId} row={row}/>)}<Pager page={page} pages={comments.data?.meta.pages??1} change={setPage}/></section>}</>}</section>;}
