import { useState } from 'react';
import { Link } from 'react-router-dom';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { t,useLanguage } from '@/i18n';
import { StationDialog } from '@/features/stations/station-dialog';
import { read,write,countries,type Offer,type Store } from './api';
import './vitrine.css';
type Row={id:string;content?:string;name?:string;url?:string;country?:string;details?:string;reason?:string;targetId?:string;targetType?:string};
export function VitrineAdmin() {
  useLanguage();const [page,setPage]=useState(1);const client=useQueryClient();const query=useQuery({queryKey:['vitrine','admin',page],queryFn:()=>read<{data:{stores:Store[];offers:Offer[];comments:Row[];suggestions:Row[];reports:Row[]};meta:{pages:number}}>(`/admin?page=${page}`)});
  const action=useMutation({mutationFn:({path,body}:{path:string;body?:unknown})=>write(path,body),onSuccess:()=>client.invalidateQueries({queryKey:['vitrine']})});
  function review(id:string,type:string,decision:string) {action.mutate({path:`/admin/review/${id}`,body:{type,action:decision}});}
  function storeForm(store?:Store) {return <StationDialog label={t(store?'Editar loja':'Cadastrar loja')}>{close=><form className="vitrine-form" onSubmit={e=>{e.preventDefault();const data=new FormData(e.currentTarget);action.mutate({path:'/admin/stores',body:{name:data.get('name'),country:data.get('country'),domains:String(data.get('domains')).split(/[\s,]+/).filter(Boolean),active:data.get('active')==='on'}},{onSuccess:close});}}><label>{t('Nome da loja')}<input name="name" required defaultValue={store?.name} readOnly={!!store} maxLength={80}/></label><label>{t('País')}<select name="country" defaultValue={store?.country??'BR'}>{Object.entries(countries).map(([id,name])=><option key={id} value={id}>{t(name)}</option>)}</select></label><label>{t('Domínios autorizados')}<textarea name="domains" defaultValue={store?.domains?.join('\n')} required/></label><p>{t('Confira os domínios oficiais antes de ativar. Subdomínios e links de consultores precisam de análise própria.')}</p><label className="vitrine-check"><input name="active" type="checkbox" defaultChecked={store?.active}/>{t('Domínios conferidos: permitir publicações')}</label><button disabled={action.isPending}>{t('Salvar')}</button>{action.isError&&<p role="alert">{t(action.error.message)}</p>}</form>}</StationDialog>;}
  return <section className="vitrine"><Link to="/vitrine">{t('Voltar à vitrine')}</Link><h1>{t('Revisar vitrine')}</h1>{query.isPending&&<p>{t('Carregando...')}</p>}{query.isError&&<p role="alert">{t(query.error.message)}</p>}{action.isError&&<p role="alert">{t(action.error.message)}</p>}{action.isSuccess&&<p role="status">{t(action.data.message)}</p>}
    {query.data&&<><div className="vitrine-options"><button disabled={action.isPending} onClick={()=>action.mutate({path:'/admin/seed'})}>{t('Preparar catálogo candidato')}</button>{storeForm()}</div>
      <details className="vitrine-review"><summary>{t('Lojas')} · {query.data.data.stores.length}</summary><p>{t('As lojas candidatas começam desativadas. A lista não representa homologação concluída.')}</p>{query.data.data.stores.map(s=><div className="vitrine-store-row" key={s.id}><div><strong>{s.name}</strong><small>{s.country} · {t(s.active?'Ativa':'Inativa')}</small></div>{storeForm(s)}</div>)}</details>
      {(['offers','comments','suggestions','reports'] as const).map((key,index)=>{const rows=query.data.data[key];const type=['OFFER','COMMENT','SUGGESTION','REPORT'][index];return <details className="vitrine-review" key={key}><summary>{t(['Ofertas pendentes','Comentários pendentes','Lojas sugeridas','Denúncias'][index])} · {rows.length}</summary>{rows.map(row=><article key={row.id}>{key==='offers'?<><h3>{(row as Offer).title}</h3><img className="vitrine-review-image" src={(row as Offer).imageUrl} alt=""/><p>{(row as Offer).description}</p><p>{(row as Offer).url}</p></>:<><h3>{(row as Row).name}</h3><p>{(row as Row).content??(row as Row).details??(row as Row).reason}</p><p>{(row as Row).url}</p>{key==='reports'&&<ReportPreview id={(row as Row).targetId!} type={(row as Row).targetType!}/>}</>}<div className="vitrine-options">{key==='reports'?<><button disabled={action.isPending} onClick={()=>review(row.id,type,'DISMISS')}>{t('Arquivar')}</button><button disabled={action.isPending} onClick={()=>review(row.id,type,'HIDE')}>{t('Retirar conteúdo')}</button></>:<><button disabled={action.isPending} onClick={()=>review(row.id,type,'APPROVE')}>{t(key==='suggestions'?'Marcar como analisada':'Aprovar')}</button><button disabled={action.isPending} onClick={()=>review(row.id,type,'HIDE')}>{t('Rejeitar')}</button></>}</div>{key==='suggestions'&&<p>{t('Após conferir, cadastre a loja e seus domínios na seção Lojas.')}</p>}</article>)}</details>;})}
      <nav className="vitrine-pager"><button disabled={page===1} onClick={()=>setPage(page-1)}>{t('Anterior')}</button><span>{page} / {query.data.meta.pages}</span><button disabled={page>=query.data.meta.pages} onClick={()=>setPage(page+1)}>{t('Próxima')}</button></nav></>}
  </section>;
}
function ReportPreview({id,type}:{id:string;type:string}) {const query=useQuery({queryKey:['vitrine','review-target',type,id],queryFn:()=>read<{data:{content?:string;title?:string;description?:string;imageUrl?:string}}>(`/admin/target/${type}/${id}`)});return <div>{query.isPending&&<p>{t('Carregando...')}</p>}{query.isError&&<p role="alert">{t('Conteúdo indisponível.')}</p>}{query.data&&<><strong>{query.data.data.title}</strong><p>{query.data.data.content??query.data.data.description}</p>{query.data.data.imageUrl&&<img className="vitrine-review-image" src={query.data.data.imageUrl} alt=""/>}</>}</div>;}
